### ISSUE TITLE
Example code doesn't compile assignment count mismatch: 2 = 1

### ISSUE THREAD

**Issue by alanef** [abhinavdahiya/go-messenger-bot#1]
example code examines err on  NewBotAPI

but  has no error return

func NewBotAPI(token string, vtoken string) *BotAPI  {
- even correcting this I'm not getting your library to work 
  my own test code / certs etc are working OK

is it still work in progress or have you got the example operational?

**Comment by abhinavdahiya** [comment]
Hey @alanef 
The work is still in progress, I'm testing this myself :)
But i have my personal try bot at https://github.com/abhinavdahiya/go-ad-bot using this lib, which seems to be working

If you could give me details on the error, I would love to help.

**Comment by alanef** [comment]
Hi @abhinavdahiya 

I see you sorted the example.

I now have it working.

The issue I had was when testing as page admin, no 'text' element was being seen.

However when I created a 'tester' on a separate Facebook account the 'text' message got passed.

This isn't an issue with your library (I could see the same issue in my basic test code) but a Facebook issue.

My bot is now working.

**Comment by abhinavdahiya** [comment]
@alanef Great
