### ISSUE TITLE
Goroutine use for listen

### ISSUE THREAD

**Issue by alanef** [abhinavdahiya/go-messenger-bot#2]
Hi

Is there any reason in your example code you are using a goroutine for the listen?

`go http.ListenAndServeTLS("0.0.0.0:8443", "cert.pem", "key.pem", mux)`

I have only ever seen using goroutines like this when one program has to listen on multiple ports.

Interest to see why you chose to do this this way?

Alan

**Comment by abhinavdahiya** [comment]
Hi @alanef 

As you know http.ListenAndServeTLS is an blocking operation ie program halts here to listen and no instructions after that will be run and setwebhook also returns a channel where you can listen for callbacks received check [here](https://godoc.org/github.com/abhinavdahiya/go-messenger-bot#BotAPI.SetWebhook)

I chose the example program to have handling the content of callback channel as main focus coz thats the main aim of the program right! :) , and use a separate goroutine to serve as listener (http.ListenAndServeTLS).

Its just a personal choice to emphasize on the main aim of this library ie to handle the callbacks

**Comment by alanef** [comment]
Many thanks for taking the time to explain.

I have only been working with Golang for a short while. I have learned a lot reading through your code.

By the way, I how have my test bot working perfectly with your routines, for text, buttons and cards.

Now on to my next task, working out how to call wit.ai effectively from my bot :)

**Comment by alanef** [comment]
p.s.  the only 'gotcha' I came across (due to lack of fully understanding the FB environment) was on 
[send](https://godoc.org/github.com/abhinavdahiya/go-messenger-bot#BotAPI.Send)   of cards or butons it is important to set notif to  SilentNotif, otherwise I got a loop.
