### ISSUE TITLE
Incoming requests not validated, may not be from Facebook

### ISSUE THREAD

**Issue by abunner** [abhinavdahiya/go-messenger-bot#3]
Looking through the Messenger platform's official sample, they use the app secret to validate that each requests actually comes from Facebook before processing it

https://github.com/fbsamples/messenger-platform-samples/blob/master/node/app.js

See the verifyRequestSignature function in app.js

Seems like a good addition to this library

**Comment by abhinavdahiya** [comment]
@abunner thanks for the suggestion, I think this commit should do the job
